### PR TITLE
Transparent item

### PR DESCRIPTION
**Pull request by kevindeedavis**

### CODE REVIEW

**Comment by jakerichan** [comment]
:+1:

**Comment by mndvns** [comment]
@jakerichan i think this merged with my https://github.com/ui-kit/ui-kit/pull/21 commit...

**Comment by camshaft** [comment]
It's cause he merged instead of rebased

**Comment by jakerichan** [comment]
Nbd, it's just weird because I saw both of these prs next to each other. So it looked like that branch was merged in then pushed up. 



—
Jake Richan

**Comment by jaydenanderson** [comment]
I think something funky happened with the Github app, or maybe this branch was accidentally started off of Mike's. Who knows. Outside of the sort stuff, it looks good. I would propose we have a like, and a dark one though. This one would be 'transparent-light', and 'transparent-dark' would just be setting background to transparent.

**Comment by kevindeedavis** [comment]
I’m not sure what happened. I didn’t merge anything (just pull, push, commit). Really weird.  


Thanks,

Kevin

**Comment by jakerichan** [comment]
This PR has been forsaken

**Comment by mndvns** [comment]
if nobody has any objections, then at the end of the day today i'll take this PR out back and put it to sleep with my rifle

**Comment by mndvns** [comment]
that background-image util is interesting, but i don't know where we're actually needing it. anybody know? @kevindeedavis did you write that?

**Comment by kevindeedavis** [comment]
I might have. To be honest I can’t recall. I would go forth and put it out of it’s misery.  


Thanks,

Kevin

**Comment by mndvns** [comment]
goodbye, code. sleep now in the fire

**Comment by jakerichan** [comment]
@mndvns I wrote that into the background image util for quiz backgrounds.  I believe it's already merged

**Pull request closed without merging**
