### PR TITLE
removed makePath method used in merge-link

### PR DESCRIPTION
**Pull request by pchatterton**

### CODE REVIEW

**Comment by mndvns** [comment]
are you guys upgrading to the react router?

**Comment by pchatterton** [comment]
no, but if you go to our dashboard right now the page refreshes every time you select a side link. We're not exactly sure what caused that but this change fixes it.

**Comment by mndvns** [comment]
ah

**Comment by jakerichan** [comment]
@mndvns @pchatterton I can't remember, what's the purpose of this component? Why would we use this over using a normal anchor?

**Comment by mndvns** [comment]
it has to do with how the router merges the queries on those anchors

**Comment by pchatterton** [comment]
The main purpose of this component is it merges query parameters. So you can select List and then a Sort option and it'll continually merge those query params (or remove them if set to null). Cameron wrote this with me back in the grotto days.

**Comment by jakerichan** [comment]
ah, okay thanks.

**Comment by jakerichan** [comment]
:+1:

**Pull request merged**
