### PR TITLE
reorganize base styles

### PR DESCRIPTION
**Pull request by mndvns**

### CODE REVIEW

**Comment by mndvns** [comment]
@jakerichan @pchatterton @bbassett @jaydenanderson :eyes: 

we discussed refactoring our base styles awhile ago, and this is more what i had in mind for ui-kit. with this approach, you have the most flexibility. here are a couple usages in apps:

app/index.ess
```
%ui-kit/skins/base.ess
```
this brings in the bare minimum styles that all of our apps need. it won't do anything to anchors, lists, headings, etc. bare minimum. why? because this is really all we want in non-movement apps (docs, static sites, etc)

app/index.ess
```
%ui-kit/skins/base.ess
%ui-kit/skins/normalize.ess
```
this brings in all of the movement styles for all tags. anchors, lists, text blocks, the whole thing.

app/index.ess
```
%ui-kit/skins/base.ess
%ui-kit/skins/headings.ess
```
naturally, this is if your app only wants headings. this way you get to opt _in_ to styles as you need, and never have to override anything.

feedback?

**Comment by jaydenanderson** [comment]
Looks good. I might prefer to see a few of those files inside of a normalize directory as base seems mostly like a reset to me, and the design team doesn't like styling base elements. That's probably just a personal preference thing as I'm not sure it really matters since you can still opt into the normalize styles.

Your call.

:+1:

**Comment by camshaft** [comment]
Movement specific stuff shouldn't really be in here. I would prefer having building blocks for a reset here and then assembling it in movement-ui-kit

**Comment by mndvns** [comment]
@camshaft yeah, i can move these to movement/ui-kit.

**Comment by jakerichan** [comment]
So are these being moved @mndvns or are we going to merge this then move them?

**Comment by mndvns** [comment]
let's merge and then move

**Pull request merged**
